<?php

return [
    'basic' => [
        'name' => 'Basic',
        'price' => 'KES 3,000',
        'amount' => 3000,
        'job_allowance' => 3,
        'duration_unit' => 'days',
        'duration_value' => 30,
        'jobs' => '3 Jobs',
        'validity' => '30 days',
        'best_for' => 'Occasional hiring',
        'features' => [
            '3 job postings',
            '30-day visibility per job',
            'Candidate applications',
            'Employer profile',
            'Application management',
            'Email application notifications',
            'Job editing',
        ],
    ],
    'starter' => [
        'name' => 'Starter',
        'price' => 'KES 10,000',
        'amount' => 10000,
        'job_allowance' => 10,
        'duration_unit' => 'days',
        'duration_value' => 60,
        'jobs' => '10 Jobs',
        'validity' => '60 days',
        'best_for' => 'Small businesses',
        'features' => [
            '10 job postings',
            '30-day visibility per job',
            'Employer profile',
            'Candidate application management',
            'Email notifications',
            'Job editing',
            'Basic employer branding',
            '1 Featured Job',
            '1 Social Media Promotion',
            'Save KES 2,500',
        ],
    ],
    'growth' => [
        'name' => 'Growth',
        'price' => 'KES 20,000',
        'amount' => 20000,
        'job_allowance' => 20,
        'duration_unit' => 'days',
        'duration_value' => 90,
        'jobs' => '20 Jobs',
        'validity' => '90 days',
        'best_for' => 'Growing companies',
        'most_popular' => true,
        'features' => [
            '20 job postings',
            '30-day visibility per job',
            'Enhanced employer profile',
            'Candidate application management',
            'Email notifications',
            'Job editing',
            'Employer branding',
            '2 Featured Jobs',
            '2 Social Media Promotions',
            '1 Homepage Feature',
            'Priority customer support',
            'Save KES 7,500',
        ],
    ],
    'business' => [
        'name' => 'Business',
        'price' => 'KES 50,000',
        'amount' => 50000,
        'job_allowance' => 50,
        'duration_unit' => 'months',
        'duration_value' => 6,
        'jobs' => '50 Jobs',
        'validity' => '6 months',
        'best_for' => 'Active recruiters',
        'features' => [
            '50 job postings',
            '30-day visibility per job',
            'Enhanced company profile',
            'Candidate application management',
            'Employer branding',
            '5 Featured Jobs',
            '3 Homepage Features',
            '5 Social Media Promotions',
            'Priority support',
            'Basic recruitment consultation',
            'Vacancy optimization',
            'Save KES 27,500',
        ],
    ],
    'enterprise' => [
        'name' => 'Enterprise',
        'price' => 'Custom',
        'amount' => null,
        'job_allowance' => 50,
        'duration_unit' => 'months',
        'duration_value' => 12,
        'jobs' => '50+ Jobs',
        'validity' => '12 months / contract terms',
        'best_for' => 'Large organisations',
        'features' => [
            'Large-volume job posting options',
            'Dedicated employer account',
            'Enhanced company profile',
            'Priority vacancy placement',
            'Featured vacancies',
            'Social media promotion',
            'Recruitment support',
            'Shortlisting support',
            'Screening services',
            'Dedicated account management',
            'Custom terms and reporting',
        ],
    ],
];